historyapp/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cities, only: [:index, :show, :new, :create, :edit, :update]
  resources :buildings, only: [:index, :show, :new, :create, :edit, :update]
  resources :landmarks, only: [:index, :show, :new, :create, :edit, :update]
  resources :figures, only: [:show, :index, :new, :create, :destroy]

  resources :users
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

historyapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

historyapp/app/models/building.rb
class Building < ApplicationRecord
  belongs_to :city, required: false
  belongs_to :figure, required: false

  validates :name, presence: true
  validates :date_built, presence: true
  validates :address, presence: true
end

historyapp/app/models/city.rb
class City < ApplicationRecord
  belongs_to :user, required: false
  has_many :buildings
  has_many :landmarks
  has_many :figures, through: :buildings
  # has_many :figures, through: :landmarks

  validates :name, presence: true, uniqueness: true

  def building_list
    self.buildings
  end

  def landmark_list
    self.landmarks
  end

  def figure_list
    self.figures
  end

end

historyapp/app/models/figure.rb
class Figure < ApplicationRecord
  has_many :landmarks
  has_many :buildings
  has_many :cities, through: :landmarks
  has_many :cities, through: :buildings

  validates :name, presence: true, uniqueness: true
  validates :birth_date, presence: true
  validates :death_date, presence: true
  validates :hometown, presence: true
  validates :profession, presence: true
  validates :gender, presence: true
  validates :bio, presence: true


end

historyapp/app/models/landmark.rb
class Landmark < ApplicationRecord
  belongs_to :city, required: false
  belongs_to :figure, required: false

  validates :name, presence: true
  validates :event_date, presence: true
  validates :address, presence: true
end

historyapp/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :cities
  has_many :buildings, through: :cities
  has_many :landmarks, through: :cities

  validates :name, uniqueness: true, presence: true
  validates :password_digest, presence: true
end

historyapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user, :require_login

  def current_user
    if session[:user_id]
      User.find(session[:user_id])
    end
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to login_path unless session.include? :user_id
  end

end

historyapp/app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

  def index
    @buildings = Building.all
  end

  def show
    @building = Building.find(params[:id])
    @figure = @building.figure
  end

  def new
    @building = Building.new
    @cities = City.all
    @figures = Figure.all
  end

  def create
    @building = Building.new(building_params)
    if @building.valid?
      @building.save
      redirect_to building_path(@building)
    else
      flash[:error] = @building.errors.full_messages
      render :new
    end
  end

  def edit
    @building = Building.find(params[:id])
    @cities = City.all
    @figures = Figure.all
  end

  def update
    @building = Building.find(params[:id])
    if @building.valid?
      @building.update(building_params)
      redirect_to building_path(@building)
    else
      flash[:error] = @building.errors.full_messages
      render :new
    end
  end

  private

  def building_params
    params.require(:building).permit(:name, :date_built, :city_id, :figure_id, :address)
  end

end

historyapp/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index]

  def index
    @cities = City.all
  end

  def show
    @city = City.find(params[:id])
  end

  def new
    @city = City.new
  end

  def create
    @city = City.new(city_params)
    if @city.valid?
      @city.save
      redirect_to city_path(@city)
    else
      flash[:error] = @city.errors.full_messages
      render :new
    end
  end

  def edit
    @city = City.find(params[:id])
  end

  def update
    @city = City.find(params[:id])
    if @city.valid?
      @city.update(city_params)
      redirect_to city_path(@city)
    else
      flash[:error] = @city.errors.full_messages
      render :edit
    end
  end

  private

  def city_params
    params.require(:city).permit(:name, :description)
  end


end

historyapp/app/controllers/figures_controller.rb
class FiguresController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index]

  def index
    @figures = Figure.all

    if params[:search]
      @figures = Figure.search(params[:search]).order("created_at DESC")
    else
      @figures = Figure.all.order('created_at DESC')
    end
  end

  def show
    @figure = Figure.find(params[:id])
    @buildings = @figure.buildings
    @landmarks = @figure.landmarks
    @cities = @figure.cities
  end

  def new
    @figure = Figure.new
  end

  def create
    @figure = Figure.new(figure_params)
    if @figure.valid?
      @figure.save
      redirect_to figure_path(@figure)
    else
      flash[:error] = @figure.errors.full_messages
      render :new
    end
  end

  def destroy
    Figure.find(params[:id]).destroy
    flash[:success] = "Figure deleted"
    redirect_to figures_path
  end

  private

  def figure_params
    params.require(:figure).permit(:name, :birth_date, :death_date, :hometown, :profession, :gender, :bio)
  end

end

historyapp/app/controllers/landmarks_controller.rb
class LandmarksController < ApplicationController

  def index
    @landmarks = Landmark.all
  end

  def show
    @landmark = Landmark.find(params[:id])
  end

  def new
    @landmark = Landmark.new
    @cities = City.all
    @figures = Figure.all
  end

  def create
    @landmark = Landmark.new(landmark_params)
    if @landmark.valid?
      @landmark.save
      redirect_to landmark_path(@landmark)
    else
      flash[:error] = @landmark.errors.full_messages
      render :new
    end
  end

  def edit
    @landmark = Landmark.find(params[:id])
    @cities = City.all
    @figures = Figure.all
  end

  def update
    @landmark = Landmark.find(params[:id])
    if @landmark.valid?
      @landmark.update(landmark_params)
      redirect_to landmark_path(@landmark)
    else
      flash[:error] = @landmark.errors.full_messages
      render :edit
    end
  end

  private

  def landmark_params
    params.require(:landmark).permit(:name, :event_date, :figure_id, :city_id, :address)
  end

end

historyapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # skip_before_action :authorized, only: [:new, :create]

  def new
  end

  def create
    @user = User.find_by(name: params[:user][:name])

    if @user && params[:password] == @user.password
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    elsif @user
      flash[:error] = ["Username or password incorrect; please try again"]
      redirect_to login_path
    else
      flash[:error] = ["Username or password incorrect; please try again"]
      redirect_to login_path
    end
  end

  def destroy
    session.delete :user_id
    redirect_to login_path
  end

end

historyapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :authorized, only: [:new, :create, :index]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.valid?
      @user.update(user_params)
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end
  # 
  # def destroy
  #   User.find(params[:id]).delete
  #   redirect_to login_path
  # end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

historyapp/app/helpers/application_helper.rb
module ApplicationHelper
end

historyapp/app/views/buildings/edit.html.erb
<% if flash[:error]%>
  <% flash[:error].each do |err| %>
    <p><%= err %></p>
  <% end%>
<% end%>

<h1>Edit This Building</h1>

<%= form_for @building do |f| %>
  Name: <%= f.text_field :name %><br><br>

  Date Built: <%= f.text_field :date_built %><br> <br>

  Address (ex: '1313 Mockingbird Lane, Springfield, MO 65738'): <%= f.text_field :address%><br><br>

  City: <%= f.collection_select(:city_id, @cities, :id, :name) %><br><br>

  Historical Figure: <%= f.collection_select(:figure_id, @figures, :id, :name) %><br><br>

  <%= f.submit %>
<% end %>

historyapp/app/views/buildings/index.html.erb
<h3>Buildings Home</h3>

<% @buildings.each do |build| %>
  <p><%= link_to build.name, build %></p>
<%end%>

<h4><%= link_to "Create New Building", new_building_path %></h4>

historyapp/app/views/buildings/new.html.erb
<% if flash[:error]%>
  <% flash[:error].each do |err| %>
    <p><%= err %></p>
  <% end%>
<% end%>

<h1>Create a New Building</h1>

<%= form_for @building do |f| %>
  Name: <%= f.text_field :name %><br><br>

  Date Built (ex: 'January 1, 2000'): <%= f.text_field :date_built %><br> <br>

  Address (ex: '1313 Mockingbird Lane, Springfield, MO 65738'): <%= f.text_field :address%><br><br>

  City ID: <%= f.number_field :city_id %><br><br>

  Historical Figure ID: <%= f.number_field :figure_id %><br><br>

  <%= f.submit %>
<% end %>

historyapp/app/views/buildings/show.html.erb
<div class="row">

  <div class="col s12 center">
    <h3><%= @building.name %></h3>
  </div>

  <div class="col s12 center">
    <h5>Date Built: <%= @building.date_built %></h5>
  </div>

  <div class="col s12 center">
    <h5>Address: <%= @building.address %></h5>
  </div>

  <div class="col s12 center">
    <% if @figure %>
      <h5>Associated People: <%= link_to @figure.name, figure_path(@figure) %></h5>
    <%end%>
  </div>

  <div class="col s12 center">
    <%= image_tag "building_#{@building.id}.jpg" %>
  </div>

</div>

<div class="row">
  <div class="col s12 center">
    <form action= "<%="/buildings/#{@building.id}/edit"%>" >
      <input type="submit" value="Edit This Building" />
    </form>
    <br>
  </div>

  <div class="col s12 center">
    <form action= "<%="/cities/#{@building.city_id}"%>" >
      <input type="submit" value="City Home" />
    </form>
</div>

historyapp/app/views/cities/index.html.erb
<div class="row">
  <br><br>
  <div class="col s12 center">
    <%= image_tag "Excited-people.jpg" %>
  </div>

  <div class="col s12 center">
    <h4>Discover something new about your city</h4>
  </div>

  <div class="col s12 center">
    <ul>
      <% @cities.each do |city| %>
        <h5><li><%= link_to city.name, city %></li></h5>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col s12 center">
    <h5>Don't see your city listed? <%= link_to "Create it here!", new_city_path %></h5>
  </div>


</div>

historyapp/app/views/cities/show.html.erb
<div class="row">

  <div class="col s12 center">
    <h3><%= @city.name %></h3>
    <h4><%= @city.description %></h4>
    <form action="<%="/cities/#{@city.id}/edit"%>">
      <input type="submit" value="Edit Information" />
    </form>
    <br>
  </div>

  <div class="col s12 center">
    <%= image_tag "city_#{@city.id}.jpg" %>
  </div>

  <div class="col 3 left center">
    <h5>Historic Buildings</h5>
    <% @city.building_list.each do |build| %>
      <p><%= link_to build.name, build %></p>
    <%end%>
    <form action="/buildings/new">
      <input type="submit" value="Create a New Building"  />
    </form>
  </div>

  <div class="col 3 offset-s1 center">
    <h5>Historic Landmarks</h5>
    <% @city.landmark_list.each do |land| %>
      <p><%= link_to land.name, land %></p>
    <%end%>
    <form action="/landmarks/new">
      <input type="submit" value="Create a New Landmark" />
    </form>
  </div>

  <div class="col 3 right center">
    <h5>Historic Figures</h5>
    <% @city.figure_list.each do |fig| %>
      <p><%= link_to fig.name, fig %></p>
    <%end%>
    <form action="/figures/new">
      <input type="submit" value="Create a New Person" />
    </form>
  </div>

</div>

historyapp/app/views/figures/index.html.erb
<div class="row">

  <div class="col s12 center">
    <h3>Historic Figures<h3>
      <p></p>
  </div>

  <div class="col s12 center">

    <% @figures.each do |fig| %>
      <h5><%= link_to fig.name, fig %></h5>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col s12 center">
    <form action="/figures/new">
      <input type="submit" value="Create a New Person" />
    </form>
  </div>
</div>

historyapp/app/views/figures/new.html.erb
<% if flash[:error]%>
  <% flash[:error].each do |err| %>
    <p><%= err %></p>
  <% end%>
<% end%>

<h1>Create a New Person</h1>

<%= form_for @figure do |f| %>
  Name: <%= f.text_field :name%><br><br>

  Birth Date (ex: 'January 1, 2000'): <%= f.text_field :birth_date%><br><br>

  Death Date (ex: 'January 1, 2000'):<br><br>
  <i>Please write "still living" if applicable</i><br>
   <%= f.text_field :death_date%><br>

  <br><br>

  Hometown (ex: 'Republic, MO'): <%= f.text_field :hometown%><br><br>

  Profession: <%= f.text_field :profession%><br><br>

  Gender (ex: 'M' or 'F'): <%= f.text_field :gender%>

  <br><br>

  Short Biography: <%= f.text_field :bio%><br><br>

  <%= f.submit %>
<% end %>

historyapp/app/views/figures/show.html.erb
<div class="row">

  <div class="col s12 center">
    <h3><%= @figure.name %></h3>
  </div>

  <div class="col s12 center">
      <%= image_tag "figure_#{@figure.id}.jpg" %>
  </div>

  <div class="col 3 center">
    <h5>Associated Buildings: </h5>
      <% @buildings.each do |build| %>
        <h5><%= link_to build.name, building_path(build) %></h5>
      <%end%>
      <br><br>
  </div>

  <div class="col 3 offset-s1 center">
    <h5>Associated Landmarks: </h5>
      <% @landmarks.each do |land| %>
        <h5><%= link_to land.name, landmark_path(land) %></h5>
      <%end%>
      <br><br>
  </div>

  <div class="col 3  center">
    <h5>Associated Cities: </h5>
      <% @cities.each do |city| %>
        <h5><%= link_to city.name, city_path(city) %></h5>
      <%end%>
      <br><br>
  </div>

  <div class="col s12 center">
    <h5>Birth Date: <%= @figure.birth_date %></h5>

    <% if @figure.death_date != "still living" %>
      <h5> Death Date: <%= @figure.death_date %></h5>
    <%end%>

    <h5>Place of Birth: <%= @figure.hometown %></h5>

    <h5>Profession: <%= @figure.profession %></h5>
    <br>
  </div>

  <div class="col s12 center">
    <h5>Biography</h5>
    <p><%= @figure.bio %></p>
  </div>


</div>

historyapp/app/views/landmarks/edit.html.erb
<% if flash[:error]%>
  <% flash[:error].each do |err| %>
    <p><%= err %></p>
  <% end%>
<% end%>

<h1>Edit Landmark</h1>

<%= form_for @landmark do |f| %>
  Name: <%= f.text_field :name %><br><br>

  Event Date (ex: 'January 1, 2000'): <%= f.text_field :event_date%><br><br>

  Address (ex: '1313 Mockingbird Lane, Springfield, MO 65738'): <%= f.text_field :address%><br><br>

  City: <%= f.collection_select(:city_id, @cities, :id, :name) %><br><br>

  Historical Figure: <%= f.collection_select(:figure_id, @figures, :id, :name) %><br><br>

  <%= f.submit, class: "btn btn-primary"  %>
<% end %>

historyapp/app/views/landmarks/index.html.erb
<h3>Landmarks Home</h3>

<% @landmarks.each do |land| %>
  <p><%= link_to land.name, land %></p>
<%end%>

<h4><%= link_to "Create New Landmark", new_landmark_path %></h4>

historyapp/app/views/landmarks/new.html.erb
<% if flash[:error]%>
  <% flash[:error].each do |err| %>
    <p><%= err %></p>
  <% end%>
<% end%>

<h1>Create a New Landmark</h1>

<%= form_for @landmark do |f| %>
  Name: <%= f.text_field :name%><br><br>

  Event Date (ex: 'January 1, 2000'): <%= f.text_field :event_date%><br><br>

  Address (ex: '1313 Mockingbird Lane, Springfield, MO 65738'): <%= f.text_field :address%><br><br>

  City ID: <%= f.number_field :city_id%><br><br>

  Historical Figure ID: <%= f.number_field :figure_id%><br><br>

  <%= f.submit %>
<% end %>

historyapp/app/views/landmarks/show.html.erb
<div class="row">

  <div class="col s12 center">
    <h3><%= @landmark.name %></h3>
  </div>

  <div class="col s12 center">
    <h5>Important Date: <%= @landmark.event_date %></h5>
  </div>

  <div class="col s12 center">
    <h5>Address: <%= @landmark.address %></h5>
  </div>

  <div class="col s12 center">
    <% if @figure %>
      <h5>Associated People: <%= link_to @figure.name, figure_path(@figure) %></h5>
    <%end%>
  </div>

  <div class="col s12 center">
    <%= image_tag "landmark_#{@landmark.id}.jpg" %>
  </div>

</div>


<div class="row">
  <div class="col s12 center">
    <form action= "<%="/landmarks/#{@landmark.id}/edit"%>" >
      <input type="submit" value="Edit This Landmark" />
    </form><br>
    <div class="col s12 center">
      <form action= "<%="/cities/#{@landmark.city_id}"%>" >
        <input type="submit" value="City Home" />
      </form>
    </div>
  </div>
</div>

historyapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Historyapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application',  media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href= 'https://fonts.googleapis.com/css?family=Quattrocento' rel='stylesheet' type='text/css'>
  </head>

  <body>

    <nav>
      <div class="nav-wrapper grey darken-1">
        <a href="#" class="brand-logo center">EXPLORE YOUR HISTORY</a>
        <ul id="nav-mobile" class="left hide-on-med-and-down">
          <li><%= link_to "HOME", cities_path%></li>
          <li><%= link_to "PEOPLE", figures_path%></li>

          <% if logged_in? %>
            <li><%= link_to "MY PROFILE", user_path(current_user)%></li>
            <li><%= link_to "LOG OUT", logout_path, method: :delete%></li>
          <%else %>
            <li><%= link_to "SIGN UP", signup_path%></li>
            <li><%= link_to "LOG IN", login_path%></li>
          <%end%>

        </ul>
      </div>
    </nav>

    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

historyapp/app/views/users/new.html.erb
<% if flash[:error]%>
  <% flash[:error].each do |err| %>
    <p><%= err %></p>
  <% end%>
<% end%>

<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.submit "Create my account"%>
    <% end %>
  </div>
</div>

historyapp/app/views/users/show.html.erb
<h1>Hello, <%= @user.name %>!</h1>

<%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-primary" %> <br> <br>


<!-- <%= link_to "Delete Profile", user_path(@user), method: :delete, class: "btn btn-primary" %> -->